spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teste_wk?useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        type: trace
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  flyway:
    locations=classpath:db/migration/

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080