CREATE TABLE pessoa (
    pes_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pes_nome VARCHAR(255),
    pes_cpf VARCHAR(14) UNIQUE,
    pes_rg VARCHAR(20),
    pes_data_nascimento VARCHAR(10),
    pes_sexo VARCHAR(10),
    pes_mae VARCHAR(255),
    pes_pai VARCHAR(255),
    pes_email VARCHAR(255),
    pes_cep VARCHAR(10),
    pes_endereco VARCHAR(255),
    pes_numero INT,
    pes_bairro VARCHAR(255),
    pes_cidade VARCHAR(255),
    pes_estado VARCHAR(2),
    pes_telefone_fixo VARCHAR(20),
    pes_celular VARCHAR(20),
    pes_altura DOUBLE,
    pes_peso DOUBLE,
    pes_tipo_sanguineo VARCHAR(5),
    pes_imc DOUBLE,
    pes_pode_doar_sangue BOOLEAN
)DEFAULT CHARSET=utf8mb4;